#pragma config(Sensor, in2,    armPot,         sensorPotentiometer)
#pragma config(Sensor, in3,    gripperPot,     sensorPotentiometer)
#pragma config(Motor,  port1,           gripperRight,  tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port6,           armTopLeft,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armBottomLeft, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           armTopRight,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           armBottomRight, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          gripperLeft,   tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Request 1 for up the arm and 0 for down the arm
void armBase(int action, gripperPotInit)
{
	gripperPotVal = SensorValue[gripperPot];
	if (action == 1)
	{
		//Hay que modificar los motores que sean los del gripper
		while ((gripperPotVal - gripperPotInit) < 1250)
		{
			gripperPotVal = SensorValue[gripperPot];
			motor[armTopLeft] = 127;
			motor[armTopRight] = 127;
			motor[armBottomLeft] = 127;
			motor[armBottomRight] = 127;
		}
	}
	else if (action == 0)
	{
		//Esta parte hay que replantear
		while ((gripperPotVal - gripperPotInit) > 1)
		{
			gripperPotVal = SensorValue[gripperPot];
			motor[armTopLeft] = -127;
			motor[armTopRight] = -127;
			motor[armBottomLeft] = -127;
			motor[armBottomRight] = -127;
		}
	}
}

////Request 1 for open the arm and 0 for close the arm
void armAction(int action)
{
	if (action == 1)
	{
		motor[gripperLeft] = speed;
		motor[gripperRight] = speed;
		} else if (action == 0) {
		motor[gripperLeft] = speed;
		motor[gripperRight] = speed;
	}
}

task main()
{
	int gripperPotVal = 0, armPotVal = 0, gripperPotInit = 0, armPotInit = 0;
	bool init = true;
	while (1)
	{
		if (init)
		{
			gripperPotInit = SensorValue[gripperPot];
			armPotInit = SensorValue[armPot];
			init = false;
		}

		armPotVal = SensorValue[armPot];
		writeDebugStreamLine("Gripper = %d", (gripperPotVal - gripperPotInit));
		writeDebugStreamLine("Arm = %d", (armPotVal - armPotInit);
		delay(1000);
	}
}
