#pragma config(Sensor, in2,    armPot,         sensorPotentiometer)
#pragma config(Sensor, in3,    gripperPot,     sensorPotentiometer)
#pragma config(Motor,  port1,           gripperRight,  tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port6,           armTopLeft,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armBottomLeft, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           armTopRight,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           armBottomRight, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          gripperLeft,   tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Request 1 for open the gripper and 0 for close the gripper
void gripperAction(int action, int gripperPotInit)
{
	int gripperPotVal = SensorValue[gripperPot];
	bool move = true;
	if (action == 1)
	{
		//Si la pinza aun no esta abierta del todo o la pinza no puede moverse entonces sigue abriendose
		while ((gripperPotVal - gripperPotInit) < 1000)
		{
			writeDebugStreamLine("Gripper = %d", (gripperPotVal - gripperPotInit));
			motor[gripperLeft] = 127;
			motor[gripperRight] = 127;
			delay(40);
			gripperPotVal = SensorValue[gripperPot];
		}

		motor[gripperLeft] = 0;
		motor[gripperRight] = 0;
	}
	else if (action == 0)
	{
		//Esta parte hay que replantear
		writeDebugStreamLine("Valor del while tiene que ser > 1: %d", (gripperPotVal - gripperPotInit));
		while ((gripperPotVal - gripperPotInit) > 1 && move)
		{
			writeDebugStreamLine("Valor %d > Valor %d", gripperPotVal, SensorValue[gripperPot] - 50);
			//Si la pinza no puede abrirse más entonces se para el movimiento, se aumenta el umbral en 10 que es la oscilación aproximada que tiene el sensar
			if (gripperPotVal > SensorValue[gripperPot] + 50) {
				move = false;
			}
			else
			{
				writeDebugStreamLine("Gripper = %d", (gripperPotVal - gripperPotInit));
				gripperPotVal = SensorValue[gripperPot];
				motor[gripperLeft] = -127;
				motor[gripperRight] = -127;
			}
			delay(50);
		}

		motor[armTopLeft] = 0;
		motor[armTopRight] = 0;
	}
}

//Request 1 for open the arm and 0 for close the arm
//void armAction(int action)
//{
//	if (action == 1)
//	{
//		motor[gripperLeft] = 127;
//		motor[gripperRight] = 127;
//		} else if (action == 0) {
//		motor[gripperLeft] = -127;
//		motor[gripperRight] = -127;
//	}
//}

task main()
{
	int gripperPotVal = 0, armPotVal = 0, gripperPotInit = 0, armPotInit = 0;
	bool init = true;
	while (1)
	{
		if (init)
		{
			clearDebugStream();
			gripperPotInit = SensorValue[gripperPot];
			armPotInit = SensorValue[armPot];
			init = false;
		}

		gripperAction(1,gripperPotInit);
		delay(500);
		int gripperPotVal = SensorValue[gripperPot];
		writeDebugStreamLine("Gripper current: %d", (gripperPotVal - gripperPotInit));
		gripperAction(0,gripperPotInit);



		delay(100000);
	}
}
