#pragma config(Sensor, in1,    gripperPot,     sensorPotentiometer)
#pragma config(Sensor, in2,    gyro,           sensorGyro)
#pragma config(Sensor, in3,    armPot,         sensorPotentiometer)
#pragma config(Sensor, dgtl1,  encL,           sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  encR,           sensorQuadEncoder)
#pragma config(Motor,  port1,           rfBase,        tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           riTower,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rbBase,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           gripper,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           roTower,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           lbBase,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           yTower,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           loTower,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           liTower,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          lfBase,        tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//r = right, l = left, b = back, m = middle, f = front, i = inner, o = outer

//*********************************************************************************************
//			Includes
//*********************************************************************************************

#include "BNSLib.h";

//*********************************************************************************************
//			Gripper Functions
//*********************************************************************************************

//Action = 1 -> Open
//Action = 0 -> Close
//Action = 2 -> Init
//Range: 800 back of robot, 3700 closed
void gripperAction(int action)
{
	if(action==1)
	{
		while(SensorValue[gripperPot]>2000)
		{
			motor[gripper] = -127;
		}
		motor[gripper]=0;
	}
	else if(action==2)
	{
		while(SensorValue[gripperPot]<1300)
		{
			motor[gripper] = 127;
		}
		motor[gripper]=0;
	}
	else
	{
		while(SensorValue[gripperPot]<3000)
		{
			motor[gripper] = 127;
		}
		motor[gripper] = 50;
	}
}

//*********************************************************************************************
//			Base Functions
//*********************************************************************************************

// This variables for the ecnoders and counter fore the PID.
int encoderL, encoderR, counter;

// Function to move the robot to the front or back.
void moveBase(int speed)
{
	motor[rbBase]=speed;
	motor[rfBase]=speed;
	motor[lbBase]=speed;
	motor[lfBase]=speed;
}

// Funtion to correct the aligment of the robot when move to the front or back.
void moveBase(int speed, int offset)
{
	motor[rbBase]=speed + offset;
	motor[rfBase]=speed + offset;
	motor[lbBase]=speed - offset;
	motor[lfBase]=speed - offset;
}

// Rotate the base clockwise or counter-clockwise.
void rotateBase(int speed)
{
	motor[rbBase]=speed;
	motor[rfBase]=speed;
	motor[lbBase]=-speed;
	motor[lfBase]=-speed;
}

// Stop moving the robot.
void stopBase()
{
	motor[rbBase]=0;
	motor[rfBase]=0;
	motor[lbBase]=0;
	motor[lfBase]=0;
}

// Convert the distance of ticks (the value of the encoder) in inches.
float ticksToInches(int ticks)
{
	float inches = ticks*((2.75*PI)/360.0)/0.9;
	return inches;
}

float inchesToTicks(int inches)
{
	float ticks = inches*(360.0/(2.75*PI))*0.9;
	return ticks;
}

// Move the base to the front. Request the distance for know how much need to move,
// the variable time is the maximun time for wait to the movement to
// prevent keep going infinitely the task if the robot can´t move and
// finally, the variable factor to reduce the velocity of the robot.
// Note: The distance in inches.
void moveBaseWithFactor(int distance, int time, float factor){
	distance = inchesToTicks(distance);
	writeDebugStreamLine("Start moveBaseFront");
	writeDebugStreamLine("Target distance = %d", distance);
	int encoderAvg = 0;
	encoderR = 0;
	encoderL = 0;
	float initialGyro = SensorValue[gyro], actualGyro = initialGyro;
	writeDebugStreamLine("Initial Gyro Position = %f", initialGyro);
	int startEncoderValueR = SensorValue[encR];
	int startEncoderValueL = SensorValue[encL];
	bool atPos=false;
	float pidMovResult;
	//float pidStraightResult;
	counter = 0;

	PID pidMovement;
	//PID pidStraight;
	PIDInit(&pidMovement, 0.5, .1, 0.25); // Set P, I, and D constants
	//PIDInit(&pidStraight, 2, 0, 0.3);//Set constants for driving straight

	clearTimer(T1);
	int timer = T1;
	while(!atPos && timer < time){
		encoderR = (SensorValue[encR] - startEncoderValueR)*-1;//Reversing
		encoderL = SensorValue[encL] - startEncoderValueL;
		encoderAvg = (encoderR+encoderL)/2;
		writeDebugStreamLine("encR = %d\tencL = %d", encoderR, encoderL);
		pidMovResult = PIDCompute(&pidMovement, distance - encoderAvg);
		//pidStraightResult = PIDCompute(&pidStraight, initialGyro - actualGyro);
		//writeDebugStreamLine("Actual Gyro Position = %f   PID = %f", actualGyro, pidStraightResult);
		moveBase(pidMovResult);
		if (abs(encoderAvg-distance)<2)
			counter++;
		if (counter >= 4)
			atPos = true;
		timer = time1[T1];
		wait1Msec(25);
		actualGyro = SensorValue[gyro];
	}
	moveBase(0);
	writeDebugStreamLine("Encoder at position = %d", encoderAvg);
}

// Move the base to the back. Request the distance for know how much need to move,
// the variable time is the maximun time for wait to the movement to
// prevent keep going infinitely the task if the robot can´t move and
// finally, the variable factor to reduce the velocity of the robot.
// Note: The distance in inches.
void moveBaseBack(int distance, int time, int slowFactor)
{
	distance = inchesToTicks(distance);

	writeDebugStreamLine("Start moveBaseFront");
	writeDebugStreamLine("Target distance = %d", distance);

	int encoderAvg = 0;
	encoderR = 0;
	encoderL = 0;
	int startEncoderValueR = SensorValue[encR];
	int startEncoderValueL = SensorValue[encL];
	bool atPos=false;
	float pidMovResult, pidStraightResult;
	counter = 0;

	PID pidMovement;
	//PID pidStraight;
	PIDInit(&pidMovement, 0.2, 0, 0.018); // Set P, I, and D constants
	//PIDInit(&pidStraight, 0.5, 0, 0);//Set constants for driving straight

	clearTimer(T1);
	int timer = T1;

	while(!atPos && timer < time)
	{
		encoderR = abs(SensorValue[encR] - startEncoderValueR);
		encoderL = abs(SensorValue[encL] - startEncoderValueL);
		writeDebugStreamLine("encoder derecho = %d", encoderR);
		writeDebugStreamLine("encoder izquierdo = %d", encoderL);
		encoderAvg = (encoderR+encoderL)/2;
		pidMovResult = PIDCompute(&pidMovement, distance - encoderAvg);
		//pidStraightResult = PIDCompute(&pidStraight, encoderL - encoderR);
		pidMovResult = pidMovResult >  127 ? 127 : pidMovResult;

		moveBase(-pidMovResult);

		if (abs(encoderAvg-distance)<2)
			counter++;
		if (counter >= 4)
			atPos = true;
		timer = time1[T1];
		wait1Msec(25);
	}
	stopBase();
	writeDebugStreamLine("Encoder at position = %d", encoderAvg);
}

// Default values for configure the gyro.
float gyroAngle;
int offsetAngle = 90;

// Configure the default values of the gyro.
void setOffsetAngle (int angle){
	offsetAngle = angle;
}

// Task for get the value of the gyro
task getGyro {
	while(1){
		gyroAngle = (SensorValue[gyro]/10.0 + offsetAngle)%360;//Offset can be changed with function.
		//writeDebugStreamLine("gyro = %d", gyroAngle);
		wait1Msec(25);																	 //Default is 90.
	}
}

// Rotate the base to one side. The variable time is the maximun time for wait to the rotation to
// prevent keep going infinitely the task if the robot can´t rotate.
// The variable angle is for the finally wanted angle.
void rotateToAngle(float targetAngle, int time){
	writeDebugStreamLine("Start rotateToAngle");
	writeDebugStreamLine("Target angle = %f", targetAngle);
	bool atGyro=false;
	float pidGyroResult;
	counter = 0;

	PID pidGyro;
	PIDInit(&pidGyro, 0.3, 0, 0.3); // Set P, I, and D constants

	clearTimer(T1);
	int timer = time1[T1];
	while(!atGyro && timer < time){
		pidGyroResult = PIDCompute(&pidGyro, targetAngle - gyroAngle);
		rotateBase(15*pidGyroResult);
		if (abs(gyroAngle-targetAngle)<0.1)
			counter++;
		if (counter > 3)
			atGyro = true;
		timer = time1[T1];
		wait1Msec(20);
	}
	stopBase();
}

// Rotate the base to one side. The variable time is the maximun time for wait to the rotation to
// prevent keep going infinitely the task if the robot can´t rotate.
// The variable angle is for the amount of angle to rotate.
void rotateThisAngle(float angle, int time){
	writeDebugStreamLine("Start rotateThisAngle");
	writeDebugStreamLine("Target angle = %f", angle);
	bool atGyro = false;
	float pidGyroResult;
	counter = 0;

	PID pidGyro;
	PIDInit(&pidGyro, 0.3, 0, 0.4); // Set P, I, and D constants

	angle = (gyroAngle + angle)%360;

	clearTimer(T1);
	int timer = time1[T1];
	while(!atGyro && timer < time){
		pidGyroResult = PIDCompute(&pidGyro, angle - gyroAngle);
		rotateBase(15*pidGyroResult);
		if (abs(gyroAngle-angle)<2)
			counter++;
		if (counter > 3)
			atGyro = true;
		timer = time1[T1];
		wait1Msec(20);
	}
	stopBase();
}

//*********************************************************************************************
//			Arm Functions
//*********************************************************************************************

// Move the arm up and down. The amximun up is the value 2200 and the maximum down is the value 0.
// Height => [0 | 2000]
int armPotInit = 0;
int gripperPotInit = 0;
void moveArmTo(int height)
{
	int currHeight = -1*(SensorValue[armPot]-armPotInit);
	if(	currHeight < height )
	{
		while(currHeight < height)
		{
			motor[riTower] = 127;
			motor[roTower] = 127;
			motor[liTower] = 127;
			motor[loTower] = 127;
			currHeight = -1*(SensorValue[armPot]-armPotInit);
			writeDebugStreamLine("%f<%f", currHeight, height);
		}
	}
	else
	{
		while(currHeight > height)
		{
			motor[riTower] = -127;
			motor[roTower] = -127;
			motor[liTower] = -127;
			motor[loTower] = -127;
			currHeight = -1*(SensorValue[armPot]-armPotInit);
		}
	}
	motor[riTower] = 0;
	motor[roTower] = 0;
	motor[liTower] = 0;
	motor[loTower] = 0;
}

void setTower(int speed)
{
	motor[riTower] = speed;
	motor[roTower] = speed;
	motor[liTower] = speed;
	motor[loTower] = speed;
}

//Up the arm, open the gripper and down the arm
void armThrow()
{
	int armPotVal = SensorValue[armPot];
	bool throw = true;
	//up the arm
	while (-(armPotVal - armPotInit) < 2200)
	{
		writeDebugStreamLine("Condición %d > 2000", (armPotVal - armPotInit));
		motor[riTower] = 127;
		motor[roTower] = 127;
		motor[liTower] = 127;
		motor[loTower] = 127;
		delay(50);
		armPotVal = SensorValue[armPot];

		if(-(armPotVal - armPotInit) > 2000 && throw)
		{
			//Open gipper
			gripperAction(1);
			throw = false;
		}
	}

	//Down the arm
	while (-(armPotVal - armPotInit) > 5)
	{
		writeDebugStreamLine("Condición %d < 5", (armPotVal - armPotInit));
		motor[riTower] = -127;
		motor[roTower] = -127;
		motor[liTower] = -127;
		motor[loTower] = -127;
		delay(50);
		armPotVal = SensorValue[armPot];
	}

	motor[riTower] = 0;
	motor[roTower] = 0;
	motor[liTower] = 0;
	motor[loTower] = 0;
}

// Move the robot to the back while throwing objects. Parameter
// height will move the arm up to that point, then the arm will
// go up while the base moves back, the base will stop and the
// gripper will open. Finally the arm will go back down.
//
//Parameter: height - Pre-Movement heigth in pot value units
void armThrowWhileMoving(int height)
{
	moveArmTo(height);
	int armPotVal = SensorValue[armPot];
	bool throw = true;
	//up the arm
	moveBase(-127);
	while (-(armPotVal - armPotInit) < 2200)
	{
		writeDebugStreamLine("Condición %d > 2000", (armPotVal - armPotInit));
		motor[riTower] = 127;
		motor[roTower] = 127;
		motor[liTower] = 127;
		motor[loTower] = 127;
		delay(50);
		armPotVal = SensorValue[armPot];

		if(-(armPotVal - armPotInit) > 2000 && throw)
		{
			//Open gipper
			gripperAction(1);
			throw = false;
		}
	}
	stopBase();
	delay(500);
	//Down the arm
	while (-(armPotVal - armPotInit) > 5)
	{
		writeDebugStreamLine("Condición %d < 5", (armPotVal - armPotInit));
		motor[riTower] = -127;
		motor[roTower] = -127;
		motor[liTower] = -127;
		motor[loTower] = -127;
		delay(50);
		armPotVal = SensorValue[armPot];
	}

	motor[riTower] = 0;
	motor[roTower] = 0;
	motor[liTower] = 0;
	motor[loTower] = 0;
}

// Move the robot to the back while throwing objects. Parameter
// height will move the arm up to that point, then the arm will
// go up while the base moves back, the base will stop and the
// gripper will open. Finally the arm will go back down.
//
//Parameter: height - Pre-Movement heigth in pot value units
//Parameter: distance - Full distance to fence
void armThrowWhileMoving(int height, float distance)
{
	int ticks = inchesToTicks(distance);
	int preEncR = SensorValue[encR];
	int preEncL = SensorValue[encL];
	int error = ticks;
	float prop = 50;
	int armPotVal = SensorValue[armPot];
	bool throw = true;
	//up the arm
	moveArmTo(height);
	while ((-(armPotVal - armPotInit) < 2200) && error>0)
	{
		error = SensorValue[encR]+SensorValue[encL]-preEncR-preEncL;
		moveBase(error*prop*-1);
		writeDebugStreamLine("Condición %d > 2000", (armPotVal - armPotInit));
		motor[riTower] = 127;
		motor[roTower] = 127;
		motor[liTower] = 127;
		motor[loTower] = 127;
		delay(50);
		armPotVal = SensorValue[armPot];

		if(-(armPotVal - armPotInit) > 2000 && throw)
		{
			//Open gipper
			gripperAction(1);
			throw = false;
		}
	}
	stopBase();
	delay(400);
	//Down the arm
	while (-(armPotVal - armPotInit) > 5)
	{
		writeDebugStreamLine("Condición %d < 5", (armPotVal - armPotInit));
		motor[riTower] = -127;
		motor[roTower] = -127;
		motor[liTower] = -127;
		motor[loTower] = -127;
		delay(50);
		armPotVal = SensorValue[armPot];
	}

	motor[riTower] = 0;
	motor[roTower] = 0;
	motor[liTower] = 0;
	motor[loTower] = 0;
}

//*********************************************************************************************
//			Other Functions
//*********************************************************************************************

void auto1()
{
	//start on tile right
	gripperAction(2);
	moveArmTo(1500);
	rotateToAngle(70, 800);
	moveBaseWithFactor(20, 2000, 1);
	rotateToAngle(90,800);
	moveBaseWithFactor(18, 1000, 1);
	moveBaseBack(23,2000,1);
	moveArmTo(50);
	rotateToAngle(180, 1000);
	moveBaseWithFactor(20, 1000, 1);
	gripperAction(0);
	moveArmTo(1900);
	setTower(20);
	moveBaseWithFactor(5,500,1);
	rotateToAngle(95, 1000);
	moveBaseWithFactor(25, 2000, 1);
	gripperAction(1);
	moveBaseBack(10, 1000, 1);
	moveArmTo(1500);
	setTower(20);
	moveBaseWithFactor(10,1000,1);
	moveBaseBack(10,1000,1);
	rotateToAngle(270, 2000);
	moveArmTo(50);
	moveBaseWithFactor(20,2000,0.7);
	gripperAction(0);
	moveBaseBack(10,1000,1);
	moveArmTo(1900);
	setTower(20);
	rotateToAngle(180,1000);
	moveBaseWithFactor(30,2000,1);
	rotateToAngle(95,1500);
	moveBaseWithFactor(25,2000,1);
	gripperAction(1);
}

//*********************************************************************************************
//			Other Functions
//*********************************************************************************************

// Inicialice BNS library and sensors.
void init()
{
	BNS();

	//Initialize Gyro
	SensorType[gyro] = sensorNone;
	wait1Msec(1000);
	SensorType[gyro] = sensorGyro;
	wait1Msec(2000);
	//End Initialize Gyro

	SensorValue[encR] = 0;
	SensorValue[encL] = 0;

	startTask(getGyro);

	clearDebugStream();
	armPotInit = SensorValue[armPot];
	gripperPotInit = SensorValue[gripperPot];
}

// Testing for the potenciometer and the ecnoder.
void test_pot_and_enc()
{
	while(1)
	{
		writeDebugStreamLine("armPot = %f", SensorValue[armPot]-armPotInit);
		writeDebugStreamLine("gripperPot = %f", SensorValue[gripperPot]-gripperPotInit);
		writeDebugStreamLine("gyro = %f", gyroAngle);
		writeDebugStreamLine("encR = %f, encL = %f", SensorValue[encR], SensorValue[encL]);
		delay(200);
	}
}

// User control code
void userControl()
{
	while(1)
	{
		motor[rfBase]= vexRT[Ch3] - vexRT[Ch4];
		motor[rbBase]= vexRT[Ch3] - vexRT[Ch4];
		motor[lfBase]= vexRT[Ch3] + vexRT[Ch4];
		motor[lbBase]= vexRT[Ch3] + vexRT[Ch4];

		motor[liTower] = vexRT[Ch2];
		motor[roTower] = vexRT[Ch2];
		motor[loTower] = vexRT[Ch2];
		motor[riTower] = vexRT[Ch2];
		motor[yTower] = vexRT[Ch2];

		if(vexRT[Btn6U])
		{
			if(SensorValue[in1]>2900 && SensorValue[in1]<3700)
				motor[gripper]=50;
			else
				motor[gripper]=127;
		}
		else if(vexRT[Btn6D])
		{
			motor[gripper] = -127;
		}
		else
			motor[gripper]=0;
	}
}

//*********************************************************************************************
//			Main Task
//*********************************************************************************************

task main()
{
	userControl();

  //init();
  //auto1();
	//test_pot_and_enc();

	//gripperAction(0);
	//armThrowWhileMoving(1300);
}
