#pragma config(Sensor, in1,    armPot,         sensorPotentiometer)
#pragma config(Sensor, in2,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  gripperRight,   sensorDigitalOut)
#pragma config(Sensor, dgtl2,  gripperLeft,    sensorDigitalOut)
#pragma config(Sensor, dgtl3,  encR,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  encL,           sensorQuadEncoder)
#pragma config(Motor,  port1,           rbBase,        tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           riTower,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rfBase,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           rmBase,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           roTower,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           lfBase,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           lmBase,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           loTower,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           liTower,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          lbBase,        tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//r = right, l = left, b = back, m = middle, f = front, i = inner, o = outer

//*********************************************************************************************
//			Includes
//*********************************************************************************************

#include "BNSLib.h";

//*********************************************************************************************
//			Gripper Functions
//*********************************************************************************************

//Action = 1 -> Open
//Action = 0 -> Close
void gripperAction(bool action)
{
	if(action)
	{
		SensorValue[gripperLeft] = 0;
		SensorValue[gripperRight] = 0;
	}
	else
	{
		SensorValue[gripperLeft] = 1;
		SensorValue[gripperRight] = 1;
	}
}

//*********************************************************************************************
//			Base Functions
//*********************************************************************************************

int encoderL, encoderR, counter;

void moveBase(int speed)
{
	motor[rbBase]=speed;
	motor[rmBase]=speed;
	motor[rfBase]=speed;
	motor[lbBase]=speed;
	motor[lmBase]=speed;
	motor[lfBase]=speed;
}

void moveBase(int speed, int offset)
{
	motor[rbBase]=speed + offset;
	motor[rmBase]=speed + offset;
	motor[rfBase]=speed + offset;
	motor[lbBase]=speed - offset;
	motor[lmBase]=speed - offset;
	motor[lfBase]=speed - offset;
}

void rotateBase(int speed)
{
	motor[rbBase]=speed;
	motor[rmBase]=speed;
	motor[rfBase]=speed;
	motor[lbBase]=-speed;
	motor[lmBase]=-speed;
	motor[lfBase]=-speed;
}

void stopBase()
{
	motor[rbBase]=0;
	motor[rmBase]=0;
	motor[rfBase]=0;
	motor[lbBase]=0;
	motor[lmBase]=0;
	motor[lfBase]=0;
}

float ticksToInches(int ticks)
{
	float inches = ticks*((2.75*PI)/360.0)/0.9;
	return inches;
}

float inchesToTicks(int inches)
{
	float ticks = inches*(360.0/(2.75*PI))*0.9;
	return ticks;
}

//Distance in inches
void moveBaseWithFactor(int distance, int time, float factor){
	distance = inchesToTicks(distance);
	writeDebugStreamLine("Start moveBaseFront");
	writeDebugStreamLine("Target distance = %d", distance);
	int encoderAvg = 0;
	encoderR = 0;
	encoderL = 0;
	float initialGyro = SensorValue[gyro], actualGyro = initialGyro;
	writeDebugStreamLine("Initial Gyro Position = %f", initialGyro);
	int startEncoderValueR = SensorValue[encR];
	int startEncoderValueL = SensorValue[encL];
	bool atPos=false;
	float pidMovResult;
	//float pidStraightResult;
	counter = 0;

	PID pidMovement;
	//PID pidStraight;
	PIDInit(&pidMovement, 0.5, .1, 0.25); // Set P, I, and D constants
	//PIDInit(&pidStraight, 2, 0, 0.3);//Set constants for driving straight

	clearTimer(T1);
	int timer = T1;
	while(!atPos && timer < time){
		encoderR = (SensorValue[encR] - startEncoderValueR)*-1;//Reversing
		encoderL = SensorValue[encL] - startEncoderValueL;
		encoderAvg = (encoderR+encoderL)/2;
		writeDebugStreamLine("encR = %d\tencL = %d", encoderR, encoderL);
		pidMovResult = PIDCompute(&pidMovement, distance - encoderAvg);
		//pidStraightResult = PIDCompute(&pidStraight, initialGyro - actualGyro);
		//writeDebugStreamLine("Actual Gyro Position = %f   PID = %f", actualGyro, pidStraightResult);
		moveBase(pidMovResult);
		if (abs(encoderAvg-distance)<2)
			counter++;
		if (counter >= 4)
			atPos = true;
		timer = time1[T1];
		wait1Msec(25);
		actualGyro = SensorValue[gyro];
	}
	moveBase(0);
	writeDebugStreamLine("Encoder at position = %d", encoderAvg);
}

void moveBaseBack(int distance, int time, int slowFactor)
{
	distance = inchesToTicks(distance);

	writeDebugStreamLine("Start moveBaseFront");
	writeDebugStreamLine("Target distance = %d", distance);

	int encoderAvg = 0;
	encoderR = 0;
	encoderL = 0;
	int startEncoderValueR = SensorValue[encR];
	int startEncoderValueL = SensorValue[encL];
	bool atPos=false;
	float pidMovResult, pidStraightResult;
	counter = 0;

	PID pidMovement;
	//PID pidStraight;
	PIDInit(&pidMovement, 0.2, 0, 0.018); // Set P, I, and D constants
	//PIDInit(&pidStraight, 0.5, 0, 0);//Set constants for driving straight

	clearTimer(T1);
	int timer = T1;

	while(!atPos && timer < time)
	{
		encoderR = abs(SensorValue[encR] - startEncoderValueR);
		encoderL = abs(SensorValue[encL] - startEncoderValueL);
		writeDebugStreamLine("encoder derecho = %d", encoderR);
		writeDebugStreamLine("encoder izquierdo = %d", encoderL);
		encoderAvg = (encoderR+encoderL)/2;
		pidMovResult = PIDCompute(&pidMovement, distance - encoderAvg);
		//pidStraightResult = PIDCompute(&pidStraight, encoderL - encoderR);
		pidMovResult = pidMovResult >  127 ? 127 : pidMovResult;

		moveBase(-pidMovResult);

		if (abs(encoderAvg-distance)<2)
			counter++;
		if (counter >= 4)
			atPos = true;
		timer = time1[T1];
		wait1Msec(25);
	}
	stopBase();
	writeDebugStreamLine("Encoder at position = %d", encoderAvg);
}

float gyroAngle;
int offsetAngle = 90;

void setOffsetAngle (int angle){
	offsetAngle = angle;
}

task getGyro {
	while(1){
		gyroAngle = (SensorValue[gyro]/10.0 + offsetAngle)%360;//Offset can be changed with function.
		//writeDebugStreamLine("gyro = %d", gyroAngle);
		wait1Msec(25);																	 //Default is 90.
	}
}

void rotateToAngle(float targetAngle, int time){
	writeDebugStreamLine("Start rotateToAngle");
	writeDebugStreamLine("Target angle = %f", targetAngle);
	bool atGyro=false;
	float pidGyroResult;
	counter = 0;

	PID pidGyro;
	PIDInit(&pidGyro, 0.1, 0, 0.3); // Set P, I, and D constants

	clearTimer(T1);
	int timer = time1[T1];
	while(!atGyro && timer < time){
		pidGyroResult = PIDCompute(&pidGyro, targetAngle - gyroAngle);
		rotateBase(12*pidGyroResult);
		if (abs(gyroAngle-targetAngle)<0.1)
			counter++;
		if (counter > 3)
			atGyro = true;
		timer = time1[T1];
		wait1Msec(20);
	}
	stopBase();
}

void rotateThisAngle(float angle, int time){
	writeDebugStreamLine("Start rotateThisAngle");
	writeDebugStreamLine("Target angle = %f", angle);
	bool atGyro = false;
	float pidGyroResult;
	counter = 0;

	PID pidGyro;
	PIDInit(&pidGyro, 0.3, 0, 0.4); // Set P, I, and D constants

	angle = (gyroAngle + angle)%360;

	clearTimer(T1);
	int timer = time1[T1];
	while(!atGyro && timer < time){
		pidGyroResult = PIDCompute(&pidGyro, angle - gyroAngle);
		rotateBase(15*pidGyroResult);
		if (abs(gyroAngle-angle)<2)
			counter++;
		if (counter > 3)
			atGyro = true;
		timer = time1[T1];
		wait1Msec(20);
	}
	stopBase();
}

//*********************************************************************************************
//			Arm Functions
//*********************************************************************************************
int armPotInit = 0;
void moveArmTo(int height)
{
	int currHeight = -1*(SensorValue[armPot]-armPotInit);
	if(	currHeight < height )
	{
		while(currHeight < height)
		{
			motor[riTower] = 127;
			motor[roTower] = 127;
			motor[liTower] = 127;
			motor[loTower] = 127;
			currHeight = -1*(SensorValue[armPot]-armPotInit);
			writeDebugStreamLine("%f<%f", currHeight, height);
		}
	}
	else
	{
		while(currHeight > height)
		{
			motor[riTower] = -127;
			motor[roTower] = -127;
			motor[liTower] = -127;
			motor[loTower] = -127;
			currHeight = -1*(SensorValue[armPot]-armPotInit);
		}
	}
	motor[riTower] = 0;
	motor[roTower] = 0;
	motor[liTower] = 0;
	motor[loTower] = 0;
}

//Up the arm, open the gripper and down the arm
void armThrow()
{
	int armPotVal = SensorValue[armPot];
	bool throw = true;
	//up the arm
	while (-(armPotVal - armPotInit) < 2200)
	{
		writeDebugStreamLine("Condición %d > 2000", (armPotVal - armPotInit));
		motor[riTower] = 127;
		motor[roTower] = 127;
		motor[liTower] = 127;
		motor[loTower] = 127;
		delay(50);
		armPotVal = SensorValue[armPot];

		if(-(armPotVal - armPotInit) > 2000 && throw)
		{
			//Open gipper
			gripperAction(1);
			throw = false;
		}
	}

	//Down the arm
	while (-(armPotVal - armPotInit) > 5)
	{
		writeDebugStreamLine("Condición %d < 5", (armPotVal - armPotInit));
		motor[riTower] = -127;
		motor[roTower] = -127;
		motor[liTower] = -127;
		motor[loTower] = -127;
		delay(50);
		armPotVal = SensorValue[armPot];
	}

	motor[riTower] = 0;
	motor[roTower] = 0;
	motor[liTower] = 0;
	motor[loTower] = 0;
}

//Parameter: Pre-Movement Heigth in pot value
void armThrowWhileMoving(int height)
{
	moveArmTo(height);
	int armPotVal = SensorValue[armPot];
	bool throw = true;
	//up the arm
	moveBase(-127);
	while (-(armPotVal - armPotInit) < 2200)
	{
		writeDebugStreamLine("Condición %d > 2000", (armPotVal - armPotInit));
		motor[riTower] = 127;
		motor[roTower] = 127;
		motor[liTower] = 127;
		motor[loTower] = 127;
		delay(50);
		armPotVal = SensorValue[armPot];

		if(-(armPotVal - armPotInit) > 2000 && throw)
		{
			//Open gipper
			gripperAction(1);
			throw = false;
		}
	}
	stopBase();
	delay(500);
	//Down the arm
	while (-(armPotVal - armPotInit) > 5)
	{
		writeDebugStreamLine("Condición %d < 5", (armPotVal - armPotInit));
		motor[riTower] = -127;
		motor[roTower] = -127;
		motor[liTower] = -127;
		motor[loTower] = -127;
		delay(50);
		armPotVal = SensorValue[armPot];
	}

	motor[riTower] = 0;
	motor[roTower] = 0;
	motor[liTower] = 0;
	motor[loTower] = 0;
}

//*********************************************************************************************
//			Other Functions
//*********************************************************************************************
void init()
{
	BNS();

	//Initialize Gyro
	SensorType[gyro] = sensorNone;
	wait1Msec(1000);
	SensorType[gyro] = sensorGyro;
	wait1Msec(2000);
	//End Initialize Gyro

	SensorValue[encR] = 0;
	SensorValue[encL] = 0;

	startTask(getGyro);

	clearDebugStream();
	armPotInit = SensorValue[armPot];
}

void test_pot_and_enc()
{
	writeDebugStreamLine("armPot = %f", SensorValue[armPot]-armPotInit);
	writeDebugStreamLine("encR = %f, encL = %f", SensorValue[encR], SensorValue[encL]);
	delay(200);
}

void userControl()
{
	while(1)
	{
		motor[rbBase]= vexRT[Ch3] - vexRT[Ch4];
		motor[rmBase]= vexRT[Ch3] - vexRT[Ch4];
		motor[rfBase]= vexRT[Ch3] - vexRT[Ch4];
		motor[lbBase]= vexRT[Ch3] + vexRT[Ch4];
		motor[lmBase]= vexRT[Ch3] + vexRT[Ch4];
		motor[lfBase]= vexRT[Ch3] + vexRT[Ch4];

		motor[liTower] = vexRT[Ch2];
		motor[loTower] = vexRT[Ch2];
		motor[riTower] = vexRT[Ch2];
		motor[riTower] = vexRT[Ch2];

		if(vexRT[Btn6U])
		{
			SensorValue[gripperLeft] = 1;
			SensorValue[gripperRight] = 1;
		}
		if(vexRT[Btn6D])
		{
			SensorValue[gripperLeft] = 0;
			SensorValue[gripperRight] = 0;
		}
	}
}

//*********************************************************************************************
//			Main Task
//*********************************************************************************************

task main()
{
	userControl();
	//init();
	//gripperAction(0);
	//armThrowWhileMoving(1300);
}
