#pragma config(Sensor, in2,    armPot,         sensorPotentiometer)
#pragma config(Sensor, in3,    gripperPotLeft, sensorPotentiometer)
#pragma config(Sensor, in4,    gripperPotRight, sensorPotentiometer)
#pragma config(Motor,  port1,           gripperRight,  tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port6,           armTopLeft,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           armBottomLeft, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           armTopRight,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           armBottomRight, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          gripperLeft,   tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Close gripper
void gripperClose(int gripperLeftInit, int gripperRightInit)
{
	motor[gripperLeft] = 127;
	delay(10);
	int gripperLeftVal = SensorValue[gripperPotLeft];
	int gripperRightVal = SensorValue[gripperPotRight];
	if ((gripperLeftInit - gripperLeftVal ) < (gripperRightInit - gripperRightVal))
	{
		motor[gripperRight] = 127;
		delay(10);
	}
	else
	{
		motor[gripperRight] = 0;
	}
}

//Open gripper
void gripperOpen(int gripperLeftInit, int gripperRightInit)
{
	motor[gripperLeft] = -127;
	delay(10);
	int gripperLeftVal = SensorValue[gripperPotLeft];
	int gripperRightVal = SensorValue[gripperPotRight];
	//writeDebugStreamLine("((%d - %d) > (%d - %d))", gripperLeftInit, gripperLeftVal, gripperRightInit, gripperRightVal);
	if ((gripperLeftInit - gripperLeftVal ) > (gripperRightInit - gripperRightVal))
	{
		motor[gripperRight] = -127;
		delay(10);
	}
	else
	{
		motor[gripperLeft] = 0;
	}
}


task main()
{
	int gripperLeftInit = 0, gripperRightInit = 0, gripperPotInit = 0, armPotInit = 0;
	bool init = true;
	while (1)
	{
		if (init)
		{
			clearDebugStream();
			gripperLeftInit = SensorValue[gripperPotLeft];
			gripperRightInit = -1 * SensorValue[gripperPotRight];
			armPotInit = SensorValue[armPot];
			init = false;
		}

		//Open gripper
		if (vexRT[Btn5U])
		{
			gripperOpen(gripperLeftInit, gripperRightInit * -1);
		}
		//Open gripper
		else if (vexRT[Btn6U])
		{
			gripperClose(gripperLeftInit, gripperRightInit * -1);
		}
		//All off
		else
		{
			motor[gripperLeft] = 0;
			motor[gripperRight] = 0;
		}
	}
}
