#pragma config(Sensor, dgtl6,  enc,            sensorQuadEncoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float enc_now, enc_last, time_now, time_last;
float rpm_calc ()
{
	enc_now = SensorValue[enc];
	time_now = nSysTime;
	float rpm = 60000.0 * (enc_now - enc_last) / (360.0 * (time_now - time_last));//Multiplicar por relacion
	enc_last = enc_now;
	time_last = time_now;
	return rpm;
}

task main()
{
	clearDebugStream();
	writeDebugStreamLine("Time(Msec)\tRPM");
	clearTimer(T2);
	while(time1[T2]<=20000)
	{
		motor[port1]=-127;
		writeDebugStreamLine("%d\t%d",time1[T2],rpm_calc());
		delay(20);
	}
}
